### PR TITLE
Add support for credentials file

### PR DESCRIPTION
**Pull request by thatnerdjosh**
This PR:

1. Allows for user to configure either a `credentials.json` file, or continue to use an API key
2. Translates usage of deprecated `transport.APIKey` to `option.WithAPIKey`

### CODE REVIEW

**Review by smartinov — APPROVED** [review]
lgtm

**Comment by smartinov** [comment]
Thanks for the pr @thatnerdjosh !

**Comment by thatnerdjosh** [comment]
@smartinov - would you be able to update the docker image to provide the newest release as a tag?

Thanks!

**Comment by smartinov** [comment]
@thatnerdjosh On my way!!

**Comment by smartinov** [comment]
@thatnerdjosh published! Seems that docker registry disabled automatic publishes, had to migrate to github actions!

**Comment by thatnerdjosh** [comment]
@smartinov - would you be able to build it specifically for the 2.1.5 version? There is some bug after that release that I am looking into that affects credential file auth

**Pull request merged**
